#!/usr/bin/bash

export customer_case=$1
export customer=$(echo $customer_case|cut -d "/" -f1)
export case=$(echo $customer_case|cut -d "/" -f2)
export full_path="/customers/$customer_case"
export cmd1="sftp -i /home/gabe/.ssh/id_rsa gabriel.ramirez@canonical.com@files.support.canonical.com:$full_path/*.xz.* /home/gabe/cases/$customer-$case 2>/dev/null"
export cmd2="sftp -i /home/gabe/.ssh/id_rsa gabriel.ramirez@canonical.com@files.support.canonical.com:$full_path/*juju* /home/gabe/cases/$customer-$case 2>/dev/null"
export cmd3="sftp -i /home/gabe/.ssh/id_rsa gabriel.ramirez@canonical.com@files.support.canonical.com:$full_path/*logs* /home/gabe/cases/$customer-$case 2>/dev/null"

mkdir "/home/gabe/cases/$customer-$case" 2&>/dev/null
cd "/home/gabe/cases/$customer-$case"
bash -c -i "$cmd1"
bash -c -i "$cmd2"
bash -c -i "$cmd3"

rm *.md5
for f in $(ls *.xz* |sort); 
  do tar xf $f; 
done;

